version: '3.8'

services:
  pocket-http-gateway:
    build:
      context: .
      target: development
    container_name: pocket-http-gateway
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 3000:${HTTP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - pocket-network

networks:
  pocket-network:
    external: true
